# Generated by Django 6.0 on 2026-02-06 13:23

import django.db.models.deletion
import django.utils.timezone
import horilla_automations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horilla_core', '0008_alter_horillaattachment_description'),
        ('horilla_mail', '0004_alter_horillamail_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Automation Condition',
                'verbose_name_plural': 'Automation Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HorillaAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('method_title', models.CharField(editable=False, max_length=100, verbose_name='Method Title')),
                ('mail_to', models.TextField(help_text="Specify recipients for email/notifications. Supports:\n- Direct email: user@example.com\n- Self: 'self' (person who triggered)\n- Instance fields: 'instance.owner.email', 'instance.created_by', 'instance.owner'\n- Multiple: comma-separated (e.g., 'self, instance.owner.email, admin@example.com')\n\nFor notifications: Use user fields directly (e.g., 'instance.owner') or email addresses.\nThe system will find users by email if an email address is provided.", verbose_name='Mail to/Notify to')),
                ('mail_detail_choice', models.TextField(default='', editable=False, verbose_name='Mail Detail Choice')),
                ('trigger', models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_create_or_update', 'Both Create and Update'), ('on_delete', 'On Delete')], max_length=20, verbose_name='Trigger')),
                ('delivery_channel', models.CharField(choices=[('mail', 'Send as Mail'), ('notification', 'Send as Notification'), ('both', 'Send as Mail and Notification')], default='mail', max_length=50, verbose_name='Choose Delivery Channel')),
                ('also_sent_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Also Send to')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mail_server', models.ForeignKey(blank=True, help_text='Select the mail server to use for sending emails. If not selected, the primary mail server will be used.', limit_choices_to={'mail_channel': 'outgoing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horilla_mail.horillamailconfiguration', verbose_name='Outgoing Mail Server')),
                ('mail_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_mail.horillamailtemplate', verbose_name='Mail Template')),
                ('model', models.ForeignKey(limit_choices_to=horilla_automations.models.limit_content_types, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Mail and Notification',
                'verbose_name_plural': 'Mail and Notifications',
            },
        ),
    ]
