# Generated by Django 6.0 on 2026-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0007_alter_horillauser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillaattachment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about the attachment.', null=True, verbose_name='Notes'),
        ),
    ]
