# Generated by Django 6.0.3 on 2026-03-13 11:02

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0011_alter_activetab_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype'),
        ),
        migrations.AlterField(
            model_name='horillaattachment',
            name='content_type',
            field=models.ForeignKey(help_text='The type of object this attachment is related to.', on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Related Object Type'),
        ),
        migrations.AlterField(
            model_name='recentlyviewed',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype'),
        ),
        migrations.CreateModel(
            name='TimelineSpanBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model name for which timeline span fields apply.', max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('start_field', models.CharField(help_text='Field used as bar start date.', max_length=100)),
                ('end_field', models.CharField(help_text='Field used as bar end date (may equal start for single-day bars).', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_span_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Timeline span settings',
                'verbose_name_plural': 'Timeline span settings',
                'unique_together': {('model_name', 'app_label', 'user')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
