# Generated by Django 6.0 on 2026-02-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunitysplit_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigDealAlert',
        ),
    ]
