# Generated by Django 6.0 on 2026-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_leadstatus_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_convert',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
