# Generated by Django 6.0.3 on 2026-03-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
        ('horilla_mail', '0005_alter_horillamail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillamail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype'),
        ),
    ]
